### ISSUE TITLE
Implement Simplified Booking Form

### ISSUE THREAD

**Issue by FlorinMiron98** [FlorinMiron98/urban-steakhouse-restaurant#1]
**User Story**
As a Regular Customer, I want to be able to book a table, using a simplified form and receive feedback when the form submission is complete.

**Acceptance Criteria**

- [x] The booking form must be easy to access from the homepage.
- [x] The form should require only essential fields (e.g., name, phone number, date, time, number of guests).
- [x] Each form field should be required
- [x] After form submission, the user should receive a confirmation message indicating success.

**Tasks**

- [x] Implement form fields for name, contact number, date, time, and number of guests.
- [x] Add validation for each form field
- [x] Create a new page containing the confirmation message for the user to be redirected to after submitting the form
