### ISSUE TITLE
Add Newsletter Signup Feature

### ISSUE THREAD

**Issue by FlorinMiron98** [FlorinMiron98/urban-steakhouse-restaurant#2]
**User Story**
As a Regular Customer, I want to sign up for newsletters, so I can stay informed about upcoming events.

**Acceptance Criteria**

- [x] The form should require only essential fields (name, email address).
- [x] After submitting the form, users should be redirected to a new page indicating successful signup.

**Tasks**

- [x] Develop the UI for the signup form with name and email inputs, as well as a button for submitting the form.
- [x] Create a new page the user should be redirected to showcasing a confirmation message after user clicks on the submission button
