### ISSUE TITLE
Enhance Menu Accessibility with Images and Descriptions

### ISSUE THREAD

**Issue by FlorinMiron98** [FlorinMiron98/urban-steakhouse-restaurant#3]
**User Story**
As a First Time Customer, I want the menu to be easily accessible and to be able to see images and read a short description about each dish.

**Acceptance Criteria**

- [x] The menu should be easily accessible from the homepage
- [x] Each dish has a high-quality image displayed alongside it as well as a concise description.
- [x] The menu is responsive and displays correctly on various devices (desktop, tablet, mobile).

**Tasks**

- [x] Develop the user interface for the menu, ensuring it matches the design mockups.
- [x] Ensure the menu adjusts appropriately across different screen sizes.
- [x] Add a high quality image, relevant description and the price for each dish or drink.
- [x] Implement alt text for images.
- [x] Optimize images and code to ensure the menu loads quickly. (use a compressor for images)
