### ISSUE TITLE
Implement Contact Form for Customer Inquiries and Feedback

### ISSUE THREAD

**Issue by FlorinMiron98** [FlorinMiron98/urban-steakhouse-restaurant#5]
**User Story**
As a Customer, I want to contact the restaurant easily through a contact form, so that I can ask questions or provide feedback.

**Acceptance Criteria**

- [x] The contact form must be easily accessible from the website(contact page or footer).
- [x] The form must include necessary fields: name, email, phone number and message
- [x] All form fields must be required
- [x] After submitting the form, the user should be redirected to a new page containing a confirmation message

**Tasks**

- [x] Create the form with the necessary fieldsets and make it responsive across all screen sizes
- [x] Implement validation by making each fieldset required
- [x] Create a new page for the user to be redirected to after submitting the form
