### ISSUE TITLE
Add Customer Reviews and Ratings Feature

### ISSUE THREAD

**Issue by FlorinMiron98** [FlorinMiron98/urban-steakhouse-restaurant#6]
**User Story**
As a Customer, I want to read reviews and ratings from other customers, so that I can gauge the quality of the restaurant.

**Acceptance Criteria**

- [x] The reviews section must be prominently displayed on the restaurant’s website and easily accessible from the main page.
- [x] Each review should contain a rating (e.g., a five star rating), the customer's name/picture and a review text

**Tasks**

- [x] Create a Bootstrap carousel that contains the reviews nicely displayed
- [x] Implement the customer's name/picture, the rating and the review text
