### ISSUE TITLE
Improve Navigation and Responsive Design

### ISSUE THREAD

**Issue by FlorinMiron98** [FlorinMiron98/urban-steakhouse-restaurant#7]
**User Story**
As a First-Time Visitor, I need easy navigation and a user-friendly design, including a responsive layout for my device, so I can find information quickly and efficiently without frustration.

**Acceptance Criteria**

- [x] The navigation links must be clear and easy to understand with logical categories for the sections (e.g, home, menu, reservation, contact etc.)
- [x] The layout must easily adapt to the screen size without the loss of functionality or readability
- [x] Elements such as buttons, images, and text must scale appropriately based on device screen size.
- [x] Ensure that all interactive elements (buttons, links) are easily clickable, even on smaller screens.
- [x] Text should have sufficient contrast against the background to be easily readable.

**Tasks**

- [x] Implement responsive design using the Bootstrap features.
- [x] Organize code in a hierarchical order so each piece of information can be distinguished.
- [x] Use HTML semantics to ensure the accessibility for screen readers.
- [x] Make sure all interactive elements have adequate size and spacing for touch navigation.
- [x] Compress images for reducing the application's loading time in order to ensure a smooth navigation between pages.
