### ISSUE TITLE
Showcase Chefs' Profiles

### ISSUE THREAD

**Issue by FlorinMiron98** [FlorinMiron98/urban-steakhouse-restaurant#8]
**User Story**
As a Potential Customer, I want to know who the restaurant's chefs are so that I can feel confident in the quality and creativity of the food.

**Acceptance Criteria**

- [x] Implement a separate section that's prominently displayed on the main page and which contains informations about the chefs.
- [x] Each chef profile must include a high-quality photo, name, title (e.g., head chef, chef), and a brief biography highlighting their background, experience, and culinary philosophy.
- [x] The chefs section must be visually appealing and align with the overall branding of the restaurant.

**Tasks**

- [x] Gather information and photos for each chef, ensuring high-quality visuals and engaging content.
- [x] Display the chef's short background using Bootstrap modals.
- [x] Design the section with a consistent format for each chef profile, focusing on aesthetics and readability.
