### ISSUE TITLE
Add Ambience Video to Enhance Customer Experience

### ISSUE THREAD

**Issue by FlorinMiron98** [FlorinMiron98/urban-steakhouse-restaurant#9]
**User Story**
As a Potential Customer, I want to watch a small video that showcases the ambience of the restaurant, so that I can get a feel for the atmosphere and overall dining experience before deciding to visit.

**Acceptance Criteria**

- [x] The video must be displayed in the homepage or the 'about' section of the website
- [x] The video must be of high quality, with clear visuals and effectively capturing the restaurant's atmosphere.
- [x] The video should be concise in order to keep the customer engaged while providing a comprehensive overview of the ambience.

**Tasks**

- [x] Implement a separate section that contains a button which opens a video modal
- [x] Compress the video so that the user doesn't wait to long for it to download
- [x] Outline key scenes to be included, focusing on the restaurant's ambience
